export const DEFAULT_WHATSAPP_API_VERSION="v22.0";
export function authConfiguration(){const google=!!process.env.AUTH_GOOGLE_ID&&!!process.env.AUTH_GOOGLE_SECRET;const secret=!!process.env.AUTH_SECRET;return {google,secret,ready:google&&secret,demoEnabled:process.env.CARESHIELD_DEMO_MODE==="true"&&process.env.NODE_ENV!=="production"};}
export type WhatsAppOutboundConfig={accessToken:string;phoneNumberId:string;businessAccountId?:string;apiVersion:string};
export function whatsAppOutboundConfig():WhatsAppOutboundConfig|null{const accessToken=process.env.WHATSAPP_ACCESS_TOKEN;const phoneNumberId=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!accessToken||!phoneNumberId)return null;return {accessToken,phoneNumberId,businessAccountId:process.env.WHATSAPP_BUSINESS_ACCOUNT_ID||undefined,apiVersion:process.env.WHATSAPP_API_VERSION||DEFAULT_WHATSAPP_API_VERSION};}
export function hasWhatsAppWebhookConfig(){return !!process.env.WHATSAPP_WEBHOOK_VERIFY_TOKEN&&!!process.env.META_APP_SECRET;}
export function emergencyWhatsAppProviderMode(){if(whatsAppOutboundConfig())return "live" as const;if(process.env.NODE_ENV!=="production"&&process.env.CARESHIELD_DEMO_MODE==="true")return "demo" as const;return "unavailable" as const;}
export function sanitizeProviderFailure(_error:unknown){return "WhatsApp provider delivery failed";}
export type DeploymentReadiness={mongo:boolean;authSecret:boolean;google:boolean;whatsAppOutbound:boolean;whatsAppWebhook:boolean;ready:boolean;releaseReady:boolean};
export function deploymentReadiness():DeploymentReadiness{const mongo=!!process.env.MONGODB_URI;const auth=authConfiguration();const whatsAppOutbound=!!whatsAppOutboundConfig();const whatsAppWebhook=hasWhatsAppWebhookConfig();const ready=mongo&&auth.secret&&auth.google;return {mongo,authSecret:auth.secret,google:auth.google,whatsAppOutbound,whatsAppWebhook,ready,releaseReady:ready&&whatsAppOutbound&&whatsAppWebhook};}
export function assertProductionReadiness(){const state=deploymentReadiness();if(process.env.NODE_ENV==="production"&&!state.ready)throw new Error("Production requires MongoDB, Auth.js secret, and Google OAuth configuration.");return state;}
