import { NextResponse } from "next/server";
import { z } from "zod";
import { requireActor } from "@/lib/session";
import { authorize } from "@/lib/authorization";
import { audit } from "@/lib/audit";
import { connectDb } from "@/lib/db";
import { Medication,MedicationAdherence,MedicineCapture,TimelineEvent } from "@/lib/models";
import { compareApprovedMedicine,doseState,scheduleForDay } from "@/lib/medication-intelligence";
import { medicineVisionProvider } from "@/lib/medicine-vision";

const adherenceSchema=z.object({action:z.literal("ADHERENCE"),medicationId:z.string().min(1),scheduledFor:z.coerce.date(),status:z.enum(["TAKEN","SKIPPED"]),note:z.string().max(500).optional()});
export async function GET(_r:Request,{params}:{params:Promise<{patientId:string}>}){try{const actor=await requireActor();const {patientId}=await params;await authorize({actor,action:"MEDICATION_INTELLIGENCE_READ",patientId});await connectDb();const medications=await Medication.find({patientId,status:"ACTIVE"}).lean();const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const records=await MedicationAdherence.find({patientId,scheduledFor:{$gte:start,$lt:end}}).lean();const byKey=new Map(records.map(x=>[`${x.medicationId}:${new Date(x.scheduledFor).getTime()}`,x]));const now=new Date();const doses=medications.flatMap(m=>scheduleForDay(m.schedule,now).map(scheduledFor=>{const record=byKey.get(`${String(m._id)}:${scheduledFor.getTime()}`);return {medicationId:String(m._id),name:m.name,dose:m.dose,scheduledFor,status:record?.status??doseState(scheduledFor,now),recordedAt:record?.recordedAt};})).sort((a,b)=>a.scheduledFor.getTime()-b.scheduledFor.getTime());return NextResponse.json({medications,doses,adherence:records});}catch{return NextResponse.json({error:"Forbidden"},{status:403});}}
export async function POST(r:Request,{params}:{params:Promise<{patientId:string}>}){try{const actor=await requireActor();const {patientId}=await params;await authorize({actor,action:"MEDICATION_INTELLIGENCE_WRITE",patientId});const type=r.headers.get("content-type")??"";await connectDb();if(type.includes("multipart/form-data")){const form=await r.formData();const file=form.get("image");if(!(file instanceof File)||file.size>5_000_000||!file.type.startsWith("image/"))return NextResponse.json({error:"Provide an image smaller than 5 MB"},{status:400});const approved=await Medication.find({patientId,status:"ACTIVE"}).lean();let extracted:{candidateName?:string;confidence:number};try{extracted=await medicineVisionProvider().extract({fileName:file.name,mimeType:file.type,bytes:file.size});}catch{extracted={confidence:0};}const compared=compareApprovedMedicine(extracted.candidateName??"",extracted.confidence,approved);const capture=await MedicineCapture.create({patientId,actorId:actor.userId,provider:"DemoMedicineVisionProvider",candidateName:extracted.candidateName,confidence:extracted.confidence,result:compared.result,matchedMedicationId:compared.medicationId});await TimelineEvent.create({patientId,kind:"MEDICINE_CAPTURE",summary:`Medicine capture: ${compared.result}`,occurredAt:new Date(),sourceId:String(capture._id),createdBy:actor.userId});await audit({actorId:actor.userId,action:"MEDICINE_CAPTURE_COMPARED",patientId,outcome:"SUCCESS",metadata:{result:compared.result,confidence:extracted.confidence}});return NextResponse.json({...compared,confidence:extracted.confidence});}
const input=adherenceSchema.parse(await r.json());if(actor.role!=="PATIENT")return NextResponse.json({error:"Only the patient may record a dose"},{status:403});const medication=await Medication.findOne({_id:input.medicationId,patientId,status:"ACTIVE"});if(!medication)return NextResponse.json({error:"Medication not found"},{status:404});const now=new Date();const state=doseState(input.scheduledFor,now);const event=await MedicationAdherence.findOneAndUpdate({medicationId:input.medicationId,scheduledFor:input.scheduledFor},{$set:{patientId,medicationId:input.medicationId,scheduledFor:input.scheduledFor,status:input.status,recordedBy:actor.userId,recordedAt:now,note:input.note}},{upsert:true,new:true});await TimelineEvent.create({patientId,kind:`MEDICATION_${input.status}`,summary:`${medication.name}: ${input.status.toLowerCase()}${state==="MISSED"?" after due time":""}`,occurredAt:now,sourceId:String(event._id),createdBy:actor.userId});await audit({actorId:actor.userId,action:`MEDICATION_${input.status}`,patientId,outcome:"SUCCESS",metadata:{medicationId:input.medicationId,scheduledFor:input.scheduledFor.toISOString()}});return NextResponse.json(event);}catch{return NextResponse.json({error:"Unable to process medication request"},{status:400});}}
